Issues fixed
MicrosoftDocs/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru pull request #8
Opened 2018-07-12 22:44 UTC by atikmapari

2018-07-12 22:45 UTC, jmazzotta commented
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/office-web-apps-server-overview.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/office-web-apps-server-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/office-web-apps-server-overview?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/plan-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/what’s-new-with-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013?branch=pr-ru-ru-8) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5Cb32f2a1b-64c0-1611-6356-3c20b113feb0%5CPullRequest%5C201807122244258258-8%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tS5X3Z3RVZn5cC7JDqjFI4MhXaGqNKRLhC%2BRXNtFc3o%3D&st=2018-07-12T22%3A40%3A36Z&se=2018-08-12T22%3A45%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-17 17:50 UTC, nivnar approved these changes

2018-07-17 17:53 UTC, nivnar requested changes
Bold text fixes have conflicts with master branch. Please resubmit PR with only fixes on missing code header. Thanks

2018-07-17 18:30 UTC, jmazzotta commented
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/apply-software-updates-to-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/configure-office-web-apps-for-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/content-roadmap-for-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/deploy-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/deploy-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/deploy-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/deploy-the-infrastructure-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/how-office-web-apps-work-on-premises-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/office-web-apps-server-overview.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/office-web-apps-server-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/office-web-apps-server-overview?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/plan-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/plan-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/plan-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/plan-office-web-apps-used-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/set-the-default-open-behavior-for-browser-enabled-documents-office-web-apps-when-used-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-server?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/technical-reference-for-office-web-apps-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/use-office-web-apps-with-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/video-configure-office-web-apps-for-sharepoint-2013?branch=pr-ru-ru-8) |
[Web-Apps-Server-loc/what’s-new-with-office-web-apps-when-used-with-sharepoint-2013.md](https://github.com/atikmapari/OfficeDocs-OfficeOnlineServer-Test-loc-pr.ru-ru/blob/issues_fixes/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/ru-ru/office/Web-Apps-Server-loc/what%E2%80%99s-new-with-office-web-apps-when-used-with-sharepoint-2013?branch=pr-ru-ru-8) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C17%5Cb32f2a1b-64c0-1611-6356-3c20b113feb0%5CPullRequest%5C201807171828574351-8%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yCNDkhnyJAdlzkHAKmDlj5sLNDtgaqxgYhWeGfvMeKg%3D&st=2018-07-17T18%3A25%3A06Z&se=2018-08-17T18%3A30%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-17 19:43 UTC, merged